name: the_gorgeous_login
description: Gorgeous Login UI

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  location: ^2.0.0
  card_settings: ^1.4.1
  geocoder: ^0.1.2
  geolocator: ^3.0.1
  google_maps_flutter: ^0.3.0+2
  font_awesome_flutter: ^8.0.1
  flutter_google_places: ^0.2.0
  image_picker: ^0.5.0+3
  flutter_image_compress: ^0.2.4
  uuid: ^2.0.1
  qr_flutter: ^2.0.0+51

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
      - assets/login_logo.png

  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf
